name: Build_Trix_APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build APK
        uses: simple-pwa/pwa-to-apk@v1
        with:
          url: "https://trix-kingdom-score--almlthb6776.replit.app"
          name: "Trix Score"
