name: Build_Trix_APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build APK
        uses: richardsauceda/pwa-to-apk@v1.1
        with:
          package-name: "com.trix.scoreboard"
          app-name: "Trix Scoreboard"
          web-url: "https://trix-kingdom-score--almlthb6776.replit.app/"
